### ISSUE TITLE
~1.1.* is not a valid Composer version constraint

### ISSUE THREAD

**Issue by jhariani** [rosette-api/php#38]
The version of the library you suggest installing - ~1.1.\* - isn't a valid version constraint:

```
$ composer require "rosette/api: ~1.1.*"

  [UnexpectedValueException]                                                  
  Could not parse version constraint ~1.1.*: Invalid version string "~1.1.*"                                                                              
```

1.1.x worked for me...

**Comment by jhariani** [comment]
Composer version 1.1.0 2016-05-10 15:21:19

**Comment by lauren12292** [comment]
Ah thanks for noticing. Will change it to ~1.1

Btw, 1.1.1 was released about an hour ago -- recommend updating. Thanks!

**Comment by jhariani** [comment]
Will do, thanks.
